name: Deploy Agents to Development

on:
  workflow_dispatch:
    inputs:
      deploy_agents:
        description: 'Deploy Agents Stack'
        required: true
        default: 'true'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    if: ${{ inputs.deploy_agents == true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install CDK and dependencies
        run: |
          npm install -g aws-cdk@latest
          pip install -r dubai-dataset/requirements.txt

      - name: CDK Bootstrap (if needed)
        run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/eu-north-1

      - name: CDK Deploy AgentsStack
        run: cdk deploy AgentsStack --app "python3 agents-app.py" --require-approval never

      - name: Post-deployment notification
        if: success()
        run: |
          echo "🚀 Successfully deployed Agents Stack to DEVELOPMENT environment"
          echo "Region: eu-north-1"